### ISSUE TITLE
Création de l'entité Reporting et de la table esgi_reporting

### ISSUE THREAD

**Issue by ChristopherDebray** [ChristopherDebray/esg_php_semestre#10]
L'entité Reporting doit contenir les propriétés suivantes :

- id : int
- date_inserted: timestamp
- date_updated: timestamp — nullable
- page_id: int — nullable
- comment_id: int — nullable
- status: 0: pending - 1: reviewed (check sous 48h, sinon tu met automatiquement en caché. Pour page remet en brouillon)

**Comment by Fansoa** [comment]
schema MCD: https://whimsical.com/4BFBL9aVgHzGVQNaTVnCW4
