### ISSUE TITLE
Création de l'entité PageComment et de la table esgi_page_comment

### ISSUE THREAD

**Issue by ChristopherDebray** [ChristopherDebray/esg_php_semestre#11]
L'entité PageComment doit contenir les propriétés suivantes :

- id : int
- date_inserted: timestamp
- status: tinyint [ 0: hidden, 1: visible ] // pending, si c’est signalé on le met en pending.
- content: varchar(255)
- user_id: int
- page_id: int

**Comment by Fansoa** [comment]
schema MCD: https://whimsical.com/4BFBL9aVgHzGVQNaTVnCW4
