### ISSUE TITLE
Création des wireframes de template de page

### ISSUE THREAD

**Issue by ChristopherDebray** [ChristopherDebray/esg_php_semestre#12]
En temps qu'utilisateur si je créer une page, je veux avoir le choix entre 3 thèmes différents, pour cela nous devons créer les wireframes associés

**Comment by Fansoa** [comment]
![Image](https://github.com/ChristopherDebray/esg_php_semestre/assets/69300731/9bfd0b42-23c1-4267-a0e2-a24bd2051698)
![Image](https://github.com/ChristopherDebray/esg_php_semestre/assets/69300731/a9cf05a5-dd49-4518-b4ad-b1b6c93a533b)
![Image](https://github.com/ChristopherDebray/esg_php_semestre/assets/69300731/e11c8d1a-5ad9-4a3b-9c77-97139a66df92)
